require 'rubygems'
require 'rake/testtask'

Rake::TestTask.new(:test_ios) do |t|
  t.test_files = FileList["**/*_test*.rb"]
  t.verbose = false
  t.warning = false
end

Rake::TestTask.new(:test_android) do |t|
  t.test_files = FileList["**/*_test*.rb"]
  t.verbose = false
  t.warning = false
end

task :default => :test_ios
