require 'rubygems'
require 'rake/testtask'

Rake::TestTask.new(:test) do |t|
  t.libs << "unit_test_sample"
  t.test_files = FileList["**/*_test*.rb"]
  t.verbose = false
  t.warning = false
end

task :default => :test
